<a href="https://colab.research.google.com/github/muhammadkarimtiu/data_science_test/blob/main/numpy_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasi

NumPy kutubxonasini chaqirib olamiz

In [ ]:
import numpy as np

Python list bilan NumPy kutubxonasidagi massivlar (arraylar) hisoblashlari orasidagi farqni ko'ramiz.

In [ ]:
my_list = list(range(100000)) # python list 0~99999  --> Normal
my_arry = np.array(range(100000)) # numpy array(massiv) 0~99999  --> Vektorlashgan

In [ ]:
%time for _ in range(10): [x*2 for x in my_list] # Normal

CPU times: user 82.3 ms, sys: 19.5 ms, total: 102 ms
Wall time: 104 ms


In [ ]:
%time for _ in range(10): my_arry*2  # Vektorlashgan

CPU times: user 4.55 ms, sys: 42 µs, total: 4.59 ms
Wall time: 3.15 ms


In [ ]:
104/3.15

33.01587301587302

# 2.1. NumPy kutubxonasi bilan ishlash

2.1.1. N-o'lchamli massiv (array)larga ishlov berish

Numpyda massiv yaratishning eng oson yo'llaridan biri bu array funksiyasi yordamida amalga oshiriladi. Va ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi Numpy arrayiga o'girib beradi.

In [ ]:
data1 = [2.5, 3.8, 40, 16] # list
arr1 = np.array(data1)

arr1

array([ 2.5,  3.8, 40. , 16. ])

In [ ]:
data2 = [[2, 45, 3, 12], [15, 2, 35, 1.5]] # list ichidagi list (nested list)
arr2 = np.array(data2)

arr2

array([[ 2. , 45. ,  3. , 12. ],
       [15. ,  2. , 35. ,  1.5]])

In [ ]:
arr1.ndim

1

In [ ]:
arr2.ndim

2

In [ ]:
data3 = [[2, 23, 33, 14], [1, 74, -5, 28], [32, 45, 22, 1]]  # list ichida list (nested list)
arr3 = np.array(data3)

In [ ]:
arr3

array([[ 2, 23, 33, 14],
       [ 1, 74, -5, 28],
       [32, 45, 22,  1]])

In [ ]:
arr3.ndim

2

In [ ]:
data3

[[2, 23, 33, 14], [1, 74, -5, 28], [32, 45, 22, 1]]

In [ ]:
arr3

array([[ 2, 23, 33, 14],
       [ 1, 74, -5, 28],
       [32, 45, 22,  1]])

In [ ]:
d3 = [[[0 for col in range(4)]for row in range(4)] for x in range(3)]

In [ ]:
d3[1][1][1] = 16

In [ ]:
d3

[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
 [[0, 0, 0, 0], [0, 16, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
 [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]

In [ ]:
arr4 = np.array(d3)

In [ ]:
arr4

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0, 16,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [ ]:
arr4.ndim

3

# Uch o'lchovli array(massiv) yaratish

In [ ]:
data5 = [[[5, 23, 21], [45, 23, 3], [21, 33, 22]],[[2, 4, 3], [2, 4, 4], [2, 4, 7]]] # python list ichida list (nested list) x,y,z

In [ ]:
data5

[[[5, 23, 21], [45, 23, 3], [21, 33, 22]], [[2, 4, 3], [2, 4, 4], [2, 4, 7]]]

In [ ]:
arr5 = np.array(data5)  # numpy array 3 o'lchovli(x, y, z)

In [ ]:
arr5

array([[[ 5, 23, 21],
        [45, 23,  3],
        [21, 33, 22]],

       [[ 2,  4,  3],
        [ 2,  4,  4],
        [ 2,  4,  7]]])

In [ ]:
arr5.ndim  # ndim metodi arrayning necha o'lchovligini aniqlab qaytaradi

3

In [ ]:
arr5[0][2][1]  # index bo'yicha 3 o'lchovli massivdan elementni chaqirish

33

In [ ]:
arr5.shape  # qator va ustunlar sonini ko'rsatadi (q, u) ko'rinishida

(2, 3, 3)

In [ ]:
arr5.size # arr5 ning elementlar soni

18

In [ ]:
arr6 = np.zeros(shape=(2, 4, 3)) # barcha elementlari 0 ga teng bo'lgan (2, 4, 3) o'lchovli massiv

In [ ]:
arr6

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
arr7 = np.ones((2, 4))  # barcha elementlari 1 ga teng bo'lgan (2, 4) o'lchovli massiv

In [ ]:
arr7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# arange funksiyasi yordamida yaratish

In [ ]:
arr8 = np.arange(4, 20, 2)

In [ ]:
arr8

array([ 4,  6,  8, 10, 12, 14, 16, 18])